### ISSUE TITLE
Dockerize Prefill & Decode Services

### ISSUE THREAD

**Issue by justintulloch** [QuadNard/split-inference-grpc-demo#11]
Add Dockerfiles for Prefill and Decode microservices.

Create two Dockerfiles under `docker/` (or at project root), for example:

- `Dockerfile.prefill:`

```sql
FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY proto/ ./proto/
COPY bitrate_pb2.py bitrate_pb2_grpc.py ./
COPY model.py server_prefill.py ./
CMD ["python", "server_prefill.py"]
```
- `Dockerfile.decode:`

```sql
FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY proto/ ./proto/
COPY bitrate_pb2.py bitrate_pb2_grpc.py ./
COPY model.py server_decode.py ./
CMD ["python", "server_decode.py"]
```
Update `docker-compose.yml` to include these two services (build from these Dockerfiles) and link them to Kafka:

```yaml 
  prefill:
    build:
      context: .
      dockerfile: Dockerfile.prefill
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  decode:
    build:
      context: .
      dockerfile: Dockerfile.decode
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
```
**Acceptance Criteria:**

- `docker build -f Dockerfile.prefill -t split-demo-prefill .` succeeds.

- `docker build -f Dockerfile.decode -t split-demo-decode .` succeeds.

- `docker-compose up -d` brings up `prefill` and `decode` containers linked to Kafka with no errors.

- Prefill container logs show “Listening on 0.0.0.0:50052”, Decode on “0.0.0.0:50053”.
